--Task 2 test
ALTER TABLE GROUPS DISABLE ALL TRIGGERS;
ALTER TABLE STUDENTS DISABLE ALL TRIGGERS;

ALTER TRIGGER GROUPS_CHECK_TRIGGER ENABLE;

INSERT INTO GROUPS(name) VALUES('group 1');
INSERT INTO GROUPS(name) VALUES('group 2');
INSERT INTO GROUPS(name) VALUES('group 3');

SELECT * FROM GROUPS;
delete from GROUPS
where id =2;
--Not unique name
INSERT INTO GROUPS(name) VALUES('group 3');

--Not unique id
INSERT INTO GROUPS(id, name) VALUES(1, 'D');

--Task 3 test
ALTER TABLE GROUPS DISABLE ALL TRIGGERS;
ALTER TABLE STUDENTS DISABLE ALL TRIGGERS;
ALTER TRIGGER FK_STUDENTS_GROUPS_TRIGGER ENABLE;

SELECT * FROM STUDENTS;
SELECT * FROM GROUPS;

DELETE FROM GROUPS WHERE id = 2;

SELECT * FROM STUDENTS;
SELECT * FROM GROUPS;

--Task 4 test
ALTER TABLE GROUPS DISABLE ALL TRIGGERS;
ALTER TABLE STUDENTS DISABLE ALL TRIGGERS;
ALTER TRIGGER STUDENTS_LOGS_TRIGGER ENABLE;
ALTER TRIGGER GROUPS_C_VAL_UPDATE_TRIGGER ENABLE;

UPDATE STUDENTS SET GROUP_ID = 2 WHERE name = 'A';

SELECT * FROM STUDENTS;
SELECT * FROM GROUPS;
SELECT * FROM LOGS;

--Task 5 test
select * FROM LOGS;
begin
    BACKUP_INFO('2023-04-05 20:10:28.011712');
end;
Select * from students;

SELECT * FROM STUDENTS;
SELECT * FROM GROUPS;
SELECT * FROM LOGS;

--Task 6 test
ALTER TRIGGER STUDENTS_CHECK_TRIGGER ENABLE;

ALTER TRIGGER GROUPS_C_VAL_UPDATE_TRIGGER ENABLE;
ALTER TABLE GROUPS DISABLE ALL TRIGGERS;

INSERT INTO STUDENTS(name, group_id) VALUES('A', 1);
INSERT INTO STUDENTS(name, group_id) VALUES('B', 2);
INSERT INTO STUDENTS(name, group_id) VALUES('C', 2);
INSERT INTO STUDENTS(name, group_id) VALUES('D', 1);
INSERT INTO STUDENTS(name, group_id) VALUES('E', 2);
INSERT INTO STUDENTS(name, group_id) VALUES('F', 1);
INSERT INTO STUDENTS(name, group_id) VALUES('G', 1);
INSERT INTO STUDENTS(name, group_id) VALUES('R', 3);
INSERT INTO STUDENTS(name, group_id) VALUES('ALEX', 1);
SELECT * FROM STUDENTS;
SELECT * FROM GROUPS;


delete from groups;
delete from students;
delete from logs;
ALTER TABLE GROUPS ENABLE ALL TRIGGERS;
ALTER TABLE STUDENTS ENABLE ALL TRIGGERS;
