ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER dev_schema2 IDENTIFIED BY 1;
CREATE USER prod_schema2 IDENTIFIED BY 1;

grant all privileges to SYSTEM;

grant all privileges to dev_schema2;

grant all privileges to prod_schema2



CREATE TABLE DEV_SCHEMA2.tab1
(
    id NUMBER NOT NULL,
    oops NUMBER,
    nm VARCHAR2(15),

    CONSTRAINT dev_tab1_pk PRIMARY KEY(id)
);

CREATE TABLE DEV_SCHEMA2.tab2
(
    id NUMBER NOT NULL,
    ind NUMBER,
    nickname VARCHAR2(15),

    CONSTRAINT dev_tab2_pk PRIMARY KEY (id)
);

CREATE TABLE DEV_SCHEMA2.tab3
(
    id NUMBER NOT NULL,
    oops NUMBER,
    name VARCHAR2(15),

    CONSTRAINT dev_tab3_pk PRIMARY KEY (id)
);

CREATE TABLE PROD_SCHEMA2.tab1
(
    id NUMBER NOT NULL,
    james NUMBER,
    post VARCHAR2(20),

    CONSTRAINT prod_tab1_pk PRIMARY KEY (id)
);

CREATE TABLE PROD_SCHEMA2.tab2
(
    id NUMBER NOT NULL,
    ind NUMBER,
    nickname VARCHAR2(15),

    CONSTRAINT prod_tab2_pk PRIMARY KEY (id)
);

CREATE TABLE PROD_SCHEMA2.tab3
(
    id NUMBER NOT NULL,
    oops NUMBER,
    name VARCHAR2(15),

    CONSTRAINT prod_tab3_pk PRIMARY KEY (id)
);

ALTER TABLE dev_schema2.tab2 ADD CONSTRAINT dev_tab2_fk_tab1 FOREIGN KEY (id) REFERENCES DEV_SCHEMA2.tab1 (id);
ALTER TABLE dev_schema2.tab1 ADD CONSTRAINT dev_tab1_fk_tab2 FOREIGN KEY (id) REFERENCES DEV_SCHEMA2.tab2 (id);

ALTER TABLE dev_schema2.tab3 ADD CONSTRAINT dev_tab3_fk_tab1 FOREIGN KEY (id) REFERENCES DEV_SCHEMA2.tab1 (id);
ALTER TABLE dev_schema2.tab3 ADD CONSTRAINT dev_tab3_fk_tab2 FOREIGN KEY (id) REFERENCES DEV_SCHEMA2.tab2 (id);

ALTER TABLE PROD_SCHEMA2.tab2 ADD CONSTRAINT prod_tab2_fk_tab3 FOREIGN KEY (id) REFERENCES PROD_SCHEMA2.tab3 (id);
ALTER TABLE PROD_SCHEMA2.tab3 ADD CONSTRAINT prod_tab3_fk_tab1 FOREIGN KEY (id) REFERENCES PROD_SCHEMA2.tab1 (id);

BEGIN
    get_tables('DEV_SCHEMA2', 'PROD_SCHEMA2');
END;


ALTER TABLE PROD_SCHEMA2.tab3 DROP CONSTRAINT PROD_TAB3_PK;

SELECT * FROM ALL_CONSTRAINTS WHERE OWNER = 'DEV_SCHEMA2' OR OWNER = 'PROD_SCHEMA2' AND CONSTRAINT_TYPE = 'P';

DROP USER DEV_SCHEMA2 CASCADE;

drop user prod_schema2 cascade;


BEGIN
   CHECK_CYCLE(DEV_SCHEMA_NAME  => 'DEV_SCHEMA2' /*IN VARCHAR2*/);
END;

DROP TABLE PROD_SCHEMA2.TAB2;
CREATE TABLE PROD_SCHEMA2.TAB2(
	ID NUMBER(22) NOT NULL,
	IND NUMBER(22),
	NICKNAME VARCHAR2(15),
	CONSTRAINT PROD_TAB2_PK PRIMARY KEY (ID ),
	CONSTRAINT PROD_TAB2_FK_TAB3 FOREIGN KEY (ID) REFERENCES PROD_SCHEMA2.TAB3(ID)
);
DROP TABLE PROD_SCHEMA2.TAB1;
CREATE TABLE PROD_SCHEMA2.TAB1(
	ID NUMBER(22) NOT NULL,
	NM VARCHAR2(15),
	OOPS NUMBER(22),
	CONSTRAINT PROD_TAB1_PK PRIMARY KEY (ID ),
	CONSTRAINT PROD_TAB1_FK_TAB2 FOREIGN KEY (ID) REFERENCES PROD_SCHEMA2.TAB2(ID)
);
DROP TABLE PROD_SCHEMA2.TAB3;
CREATE TABLE PROD_SCHEMA2.TAB3(
	ID NUMBER(22) NOT NULL,
	NAME VARCHAR2(15),
	OOPS NUMBER(22),
	CONSTRAINT PROD_TAB3_PK PRIMARY KEY (ID )
);

CREATE INDEX dev_schema2.TEST_INDEX1 on dev_schema2.tab1(name);

CREATE INDEX dev_schema2.TEST_INDEX2 on dev_schema2.tab2(name);

CREATE INDEX dev_schema2.TEST_INDEX3 on dev_schema2.tab3(name);

CREATE INDEX prod_schema2.TEST_INDEX4 on prod_schema2.tab1(name);
CREATE INDEX prod_schema2.TEST_INDEX5 on prod_schema2.tab2(name);
CREATE INDEX prod_schema2.TEST_INDEX6 on prod_schema2.tab3(name);




CREATE TABLE dev_schema2.TEST_TABLE1
(
    id NUMBER,
    name VARCHAR2(30),
    table3_id NUMBER,
    CONSTRAINT pk_test1_id PRIMARY KEY (id),
    CONSTRAINT fk_test1_id FOREIGN KEY (table3_id) REFERENCES dev_schema2.TEST_TABLE3(id)
);

CREATE TABLE prod_schema2.TEST_TABLE1
(
    id NUMBER,
    name VARCHAR2(30),
    CONSTRAINT pk_test1_id PRIMARY KEY (id)
);

CREATE TABLE dev_schema2.TEST_TABLE2
(
    id NUMBER,
    name VARCHAR2(30),
    table1_id NUMBER,
    CONSTRAINT pk_test2_id PRIMARY KEY (id),
    CONSTRAINT fk_test2_id FOREIGN KEY (table1_id) REFERENCES dev_schema2.TEST_TABLE1(id)
);

CREATE TABLE dev_schema2.TEST_TABLE3
(
    id NUMBER,
    name VARCHAR2(30),
    CONSTRAINT pk_test3_id PRIMARY KEY (id)
);

ALTER TABLE dev_schema2.TEST_TABLE1
ADD table3_id NUMBER;

ALTER TABLE dev_schema2.TEST_TABLE1
ADD CONSTRAINT fk_test1_id FOREIGN KEY (table3_id) REFERENCES dev_schema2.TEST_TABLE3(id);
/

CREATE OR REPLACE FUNCTION dev_schema2.TEST_FUNC(num NUMBER) RETURN NUMBER AS

BEGIN
    return NUM;
END;
/

CREATE OR REPLACE FUNCTION dev_schema2.TEST_FUNC(num NUMBER) RETURN NUMBER AS

BEGIN
    return NUM + 2;
END;
/


CREATE OR REPLACE PROCEDURE dev_schema2.TEST_PROC(num NUMBER) AS

BEGIN
    dbms_output.PUT_LINE(num);
END;
/

CREATE OR REPLACE PROCEDURE prod_schema2.TEST_PROC(num NUMBER) AS

BEGIN
    dbms_output.PUT_LINE(num);
END;
/

CREATE INDEX dev_schema2.TEST_INDEX1 on dev_schema2.TEST_TABLE1(name);
CREATE INDEX prod_schema2.TEST_INDEX2 on prod_schema2.TEST_TABLE1(name);

BEGIN
    CHECK_CYCLE('DEV_SCHEMA2');
END;

BEGIN
    EXECUTE_SCRIPT('DEV_SCHEMA2','PROD_SCHEMA2');
END;

DELETE FROM cycle_check;
DROP USER dev_schema2 CASCADE;
DROP USER prod_schema2 CASCADE;
Select * from CYCLE_CHECK;


CREATE TABLE dev_schema2.TEST_TABLE3
(
    id NUMBER,
    name VARCHAR2(30),
    CONSTRAINT pk_test3_id PRIMARY KEY (id)
);

CREATE TABLE dev_schema2.TEST_TABLE2
(
    id NUMBER,
    name VARCHAR2(30),
    CONSTRAINT pk_test2_id PRIMARY KEY (id)
);

CREATE TABLE dev_schema2.TEST_TABLE1
(
    id NUMBER,
    name VARCHAR2(30),
    CONSTRAINT pk_test1_id PRIMARY KEY (id)
);

ALTER TABLE dev_schema2.TEST_TABLE2
ADD table11_id NUMBER;

ALTER TABLE dev_schema2.TEST_TABLE2
ADD CONSTRAINT fk_test2_id FOREIGN KEY (table11_id) REFERENCES dev_schema2.TEST_TABLE1(id);
/

ALTER TABLE dev_schema2.TEST_TABLE1
ADD table33_id NUMBER;

ALTER TABLE dev_schema2.TEST_TABLE1
ADD CONSTRAINT fk_test1_id FOREIGN KEY (table33_id) REFERENCES dev_schema2.TEST_TABLE3(id);
/

SELECT * FROM ALL_CONSTRAINTS WHERE OWNER = 'DEV_SCHEMA2';
ALTER TABLE DEV_SCHEMA2.TEST_TABLE22 DROP CONSTRAINT fk_test22_id;
ALTER TABLE DEV_SCHEMA2.TEST_TABLE22 DROP CONSTRAINT fk_test22_id;
ALTER TABLE DEV_SCHEMA2.TEST_TABLE22 DROP CONSTRAINT fk_test22_id;



BEGIN
    EXECUTE_SCRIPT('DEV_SCHEMA2','PROD_SCHEMA2');
END;
